"""
SHYBRID
Copyright (C) 2018  Jasper Wouters

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShyBride(object):
    def setupUi(self, ShyBride):
        ShyBride.setObjectName("ShyBride")
        ShyBride.resize(1186, 807)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShyBride.sizePolicy().hasHeightForWidth())
        ShyBride.setSizePolicy(sizePolicy)
        ShyBride.setTabShape(QtWidgets.QTabWidget.Rounded)
        ShyBride.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(ShyBride)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.btnDataSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDataSelect.setObjectName("btnDataSelect")
        self.verticalLayout.addWidget(self.btnDataSelect)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listClusterSelect = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listClusterSelect.sizePolicy().hasHeightForWidth())
        self.listClusterSelect.setSizePolicy(sizePolicy)
        self.listClusterSelect.setObjectName("listClusterSelect")
        self.listClusterSelect.addItem("")
        self.horizontalLayout.addWidget(self.listClusterSelect)
        self.fieldWindowSize = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldWindowSize.sizePolicy().hasHeightForWidth())
        self.fieldWindowSize.setSizePolicy(sizePolicy)
        self.fieldWindowSize.setText("")
        self.fieldWindowSize.setFrame(False)
        self.fieldWindowSize.setReadOnly(False)
        self.fieldWindowSize.setObjectName("fieldWindowSize")
        self.horizontalLayout.addWidget(self.fieldWindowSize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btnDraw.setEnabled(False)
        self.btnDraw.setAutoDefault(False)
        self.btnDraw.setDefault(False)
        self.btnDraw.setObjectName("btnDraw")
        self.horizontalLayout_13.addWidget(self.btnDraw)
        self.btnMagic = QtWidgets.QPushButton(self.centralwidget)
        self.btnMagic.setEnabled(False)
        self.btnMagic.setObjectName("btnMagic")
        self.horizontalLayout_13.addWidget(self.btnMagic)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.btnTemplateImport = QtWidgets.QPushButton(self.centralwidget)
        self.btnTemplateImport.setEnabled(False)
        self.btnTemplateImport.setObjectName("btnTemplateImport")
        self.verticalLayout.addWidget(self.btnTemplateImport)
        self.btnTemplateExport = QtWidgets.QPushButton(self.centralwidget)
        self.btnTemplateExport.setEnabled(False)
        self.btnTemplateExport.setObjectName("btnTemplateExport")
        self.verticalLayout.addWidget(self.btnTemplateExport)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.radioTemplate = QtWidgets.QRadioButton(self.centralwidget)
        self.radioTemplate.setEnabled(False)
        font = QtGui.QFont()
        font.setKerning(True)
        self.radioTemplate.setFont(font)
        self.radioTemplate.setMouseTracking(True)
        self.radioTemplate.setShortcut("")
        self.radioTemplate.setCheckable(True)
        self.radioTemplate.setChecked(True)
        self.radioTemplate.setAutoExclusive(True)
        self.radioTemplate.setObjectName("radioTemplate")
        self.verticalLayout.addWidget(self.radioTemplate)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.zeroForceFraction = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zeroForceFraction.setEnabled(False)
        self.zeroForceFraction.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.zeroForceFraction.setInputMethodHints(QtCore.Qt.ImhNone)
        self.zeroForceFraction.setFrame(False)
        self.zeroForceFraction.setReadOnly(False)
        self.zeroForceFraction.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.zeroForceFraction.setAccelerated(False)
        self.zeroForceFraction.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.zeroForceFraction.setKeyboardTracking(False)
        self.zeroForceFraction.setDecimals(2)
        self.zeroForceFraction.setMaximum(100.0)
        self.zeroForceFraction.setSingleStep(1.0)
        self.zeroForceFraction.setProperty("value", 3.0)
        self.zeroForceFraction.setObjectName("zeroForceFraction")
        self.horizontalLayout_11.addWidget(self.zeroForceFraction)
        self.zeroForceLabel = QtWidgets.QLabel(self.centralwidget)
        self.zeroForceLabel.setEnabled(False)
        self.zeroForceLabel.setObjectName("zeroForceLabel")
        self.horizontalLayout_11.addWidget(self.zeroForceLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioFit = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFit.setEnabled(False)
        self.radioFit.setObjectName("radioFit")
        self.horizontalLayout_12.addWidget(self.radioFit)
        self.labelFit = QtWidgets.QLabel(self.centralwidget)
        self.labelFit.setText("")
        self.labelFit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFit.setObjectName("labelFit")
        self.horizontalLayout_12.addWidget(self.labelFit)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLeftSpike = QtWidgets.QPushButton(self.centralwidget)
        self.btnLeftSpike.setEnabled(False)
        self.btnLeftSpike.setObjectName("btnLeftSpike")
        self.horizontalLayout_4.addWidget(self.btnLeftSpike)
        self.btnRightSpike = QtWidgets.QPushButton(self.centralwidget)
        self.btnRightSpike.setEnabled(False)
        self.btnRightSpike.setObjectName("btnRightSpike")
        self.horizontalLayout_4.addWidget(self.btnRightSpike)
        self.labelSpike = QtWidgets.QLabel(self.centralwidget)
        self.labelSpike.setEnabled(False)
        self.labelSpike.setText("")
        self.labelSpike.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSpike.setObjectName("labelSpike")
        self.horizontalLayout_4.addWidget(self.labelSpike)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.checkBoxLower = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLower.setEnabled(False)
        self.checkBoxLower.setObjectName("checkBoxLower")
        self.horizontalLayout_2.addWidget(self.checkBoxLower)
        self.labelLB = QtWidgets.QLabel(self.centralwidget)
        self.labelLB.setEnabled(False)
        self.labelLB.setText("")
        self.labelLB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLB.setObjectName("labelLB")
        self.horizontalLayout_2.addWidget(self.labelLB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.checkBoxUpper = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxUpper.setEnabled(False)
        self.checkBoxUpper.setObjectName("checkBoxUpper")
        self.horizontalLayout_5.addWidget(self.checkBoxUpper)
        self.labelUB = QtWidgets.QLabel(self.centralwidget)
        self.labelUB.setEnabled(False)
        self.labelUB.setText("")
        self.labelUB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUB.setObjectName("labelUB")
        self.horizontalLayout_5.addWidget(self.labelUB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.radioMove = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMove.setEnabled(False)
        self.radioMove.setCheckable(True)
        self.radioMove.setObjectName("radioMove")
        self.verticalLayout.addWidget(self.radioMove)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnMoveLeft = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoveLeft.setEnabled(False)
        self.btnMoveLeft.setObjectName("btnMoveLeft")
        self.horizontalLayout_6.addWidget(self.btnMoveLeft)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnMoveUp = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoveUp.setEnabled(False)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.verticalLayout_2.addWidget(self.btnMoveUp)
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setEnabled(False)
        self.btnReset.setObjectName("btnReset")
        self.verticalLayout_2.addWidget(self.btnReset)
        self.btnMoveDown = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoveDown.setEnabled(False)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.verticalLayout_2.addWidget(self.btnMoveDown)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.btnMoveRight = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoveRight.setEnabled(False)
        self.btnMoveRight.setObjectName("btnMoveRight")
        self.horizontalLayout_6.addWidget(self.btnMoveRight)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.checkCustomSNR = QtWidgets.QCheckBox(self.centralwidget)
        self.checkCustomSNR.setEnabled(False)
        self.checkCustomSNR.setObjectName("checkCustomSNR")
        self.horizontalLayout_14.addWidget(self.checkCustomSNR)
        self.spinSNR = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinSNR.setEnabled(False)
        self.spinSNR.setFrame(False)
        self.spinSNR.setMinimum(-99.0)
        self.spinSNR.setMaximum(99.0)
        self.spinSNR.setProperty("value", 10.0)
        self.spinSNR.setObjectName("spinSNR")
        self.horizontalLayout_14.addWidget(self.spinSNR)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.checkHeatMap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkHeatMap.setEnabled(False)
        self.checkHeatMap.setChecked(True)
        self.checkHeatMap.setObjectName("checkHeatMap")
        self.horizontalLayout_7.addWidget(self.checkHeatMap)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelLow = QtWidgets.QLabel(self.centralwidget)
        self.labelLow.setEnabled(False)
        self.labelLow.setText("")
        self.labelLow.setObjectName("labelLow")
        self.horizontalLayout_10.addWidget(self.labelLow)
        self.labelHigh = QtWidgets.QLabel(self.centralwidget)
        self.labelHigh.setEnabled(False)
        self.labelHigh.setText("")
        self.labelHigh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHigh.setObjectName("labelHigh")
        self.horizontalLayout_10.addWidget(self.labelHigh)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.colorBar = QtWidgets.QGridLayout()
        self.colorBar.setObjectName("colorBar")
        self.verticalLayout.addLayout(self.colorBar)
        self.btnMove = QtWidgets.QPushButton(self.centralwidget)
        self.btnMove.setEnabled(False)
        self.btnMove.setObjectName("btnMove")
        self.verticalLayout.addWidget(self.btnMove)
        self.btnUndo = QtWidgets.QPushButton(self.centralwidget)
        self.btnUndo.setEnabled(False)
        self.btnUndo.setObjectName("btnUndo")
        self.verticalLayout.addWidget(self.btnUndo)
        spacerItem8 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.progressLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressLabel.setText("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.verticalLayout.addWidget(self.progressLabel)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.labelPlotControl = QtWidgets.QLabel(self.centralwidget)
        self.labelPlotControl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPlotControl.sizePolicy().hasHeightForWidth())
        self.labelPlotControl.setSizePolicy(sizePolicy)
        self.labelPlotControl.setObjectName("labelPlotControl")
        self.horizontalLayout_9.addWidget(self.labelPlotControl)
        self.btnResetZoom = QtWidgets.QToolButton(self.centralwidget)
        self.btnResetZoom.setObjectName("btnResetZoom")
        self.horizontalLayout_9.addWidget(self.btnResetZoom)
        self.btnZoom = QtWidgets.QToolButton(self.centralwidget)
        self.btnZoom.setObjectName("btnZoom")
        self.horizontalLayout_9.addWidget(self.btnZoom)
        self.btnPan = QtWidgets.QToolButton(self.centralwidget)
        self.btnPan.setObjectName("btnPan")
        self.horizontalLayout_9.addWidget(self.btnPan)
        self.plotTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTitle.sizePolicy().hasHeightForWidth())
        self.plotTitle.setSizePolicy(sizePolicy)
        self.plotTitle.setText("")
        self.plotTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.plotTitle.setObjectName("plotTitle")
        self.horizontalLayout_9.addWidget(self.plotTitle)
        self.btnSave = QtWidgets.QToolButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_9.addWidget(self.btnSave)
        self.plotLayout.addLayout(self.horizontalLayout_9)
        self.plotCanvas = QtWidgets.QGridLayout()
        self.plotCanvas.setObjectName("plotCanvas")
        self.plotLayout.addLayout(self.plotCanvas)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setTracking(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.plotLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout_3.addLayout(self.plotLayout)
        ShyBride.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShyBride)
        QtCore.QMetaObject.connectSlotsByName(ShyBride)

    def retranslateUi(self, ShyBride):
        _translate = QtCore.QCoreApplication.translate
        ShyBride.setWindowTitle(_translate("ShyBride", "SHYBRID: open-source spike hybridizer for extracellular recordings"))
        self.btnDataSelect.setText(_translate("ShyBride", "select data"))
        self.listClusterSelect.setCurrentText(_translate("ShyBride", "select cluster"))
        self.listClusterSelect.setItemText(0, _translate("ShyBride", "select cluster"))
        self.fieldWindowSize.setPlaceholderText(_translate("ShyBride", "window (ms)"))
        self.btnDraw.setText(_translate("ShyBride", "draw template"))
        self.btnMagic.setText(_translate("ShyBride", "auto hybrid"))
        self.btnTemplateImport.setText(_translate("ShyBride", "import template"))
        self.btnTemplateExport.setText(_translate("ShyBride", "export template"))
        self.label.setText(_translate("ShyBride", "Display options"))
        self.radioTemplate.setText(_translate("ShyBride", "display template"))
        self.zeroForceLabel.setText(_translate("ShyBride", "zero force fraction (%)"))
        self.radioFit.setText(_translate("ShyBride", "inspect template fit"))
        self.btnLeftSpike.setText(_translate("ShyBride", "←"))
        self.btnRightSpike.setText(_translate("ShyBride", "→"))
        self.checkBoxLower.setText(_translate("ShyBride", "set fitting factor lower bound"))
        self.checkBoxUpper.setText(_translate("ShyBride", "set fitting factor upper bound"))
        self.radioMove.setText(_translate("ShyBride", "relocate unit"))
        self.btnMoveLeft.setText(_translate("ShyBride", "←"))
        self.btnMoveUp.setText(_translate("ShyBride", "↑"))
        self.btnReset.setText(_translate("ShyBride", "reset"))
        self.btnMoveDown.setText(_translate("ShyBride", "↓"))
        self.btnMoveRight.setText(_translate("ShyBride", "→"))
        self.checkCustomSNR.setText(_translate("ShyBride", "enforce custom SNR (dB):"))
        self.checkHeatMap.setText(_translate("ShyBride", "show mean spike rate (Hz)"))
        self.btnMove.setText(_translate("ShyBride", "(re)insert template"))
        self.btnUndo.setText(_translate("ShyBride", "undo insert"))
        self.labelPlotControl.setText(_translate("ShyBride", "plot control"))
        self.btnResetZoom.setText(_translate("ShyBride", "reset"))
        self.btnZoom.setText(_translate("ShyBride", "zoom"))
        self.btnPan.setText(_translate("ShyBride", "move"))
        self.btnSave.setText(_translate("ShyBride", "export plot"))

